# Generated by Django 5.2 on 2025-06-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['state', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Australia', max_length=100)),
                ('sales_tax_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sales_tax_start_date', models.DateField(blank=True, null=True)),
                ('document_culture', models.CharField(default='en-AU', max_length=10)),
                ('system_culture', models.CharField(default='en-AU', max_length=10)),
                ('currency', models.CharField(default='AUD', max_length=10)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('state_tax_name', models.CharField(blank=True, max_length=100, null=True)),
                ('state_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('state_tax_start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'States/Provinces',
                'ordering': ['country', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_type', models.CharField(max_length=100)),
                ('is_electric', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('fuel_unit', models.CharField(default='Liter', max_length=50)),
                ('fuel_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_default', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('fuel_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['fuel_type'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=100)),
                ('fuel_capacity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['model_name'],
                'managed': False,
            },
        ),
    ]
