# Generated by Django 5.2 on 2025-06-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_city_country_stateprovince_vehiclefuel_vehiclemake_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='app_city',
        ),
        migrations.AlterModelTable(
            name='country',
            table='app_country',
        ),
        migrations.AlterModelTable(
            name='stateprovince',
            table='app_stateprovince',
        ),
        migrations.AlterModelTable(
            name='vehiclefuel',
            table='app_vehiclefuel',
        ),
        migrations.AlterModelTable(
            name='vehiclemake',
            table='app_vehiclemake',
        ),
        migrations.AlterModelTable(
            name='vehiclemodel',
            table='app_vehiclemodel',
        ),
    ]
