# Generated by Django 5.2 on 2025-04-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0003_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='bookings.driver'),
        ),
    ]
