# Generated by Django 5.2 on 2025-04-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Car Categories',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('bags', models.PositiveIntegerField()),
                ('doors', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], max_length=1)),
                ('air_conditioning', models.BooleanField(default=True)),
                ('image_url', models.URLField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('comparison_provider1_name', models.CharField(blank=True, max_length=50)),
                ('comparison_provider1_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('comparison_provider2_name', models.CharField(blank=True, max_length=50)),
                ('comparison_provider2_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('locations', models.ManyToManyField(related_name='available_cars', to='locations.location')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cars.car')),
            ],
        ),
    ]
