# Generated by Django 5.2 on 2025-06-06 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_type', models.CharField(max_length=50)),
                ('rate_type', models.CharField(max_length=50)),
                ('web_available', models.BooleanField(default=False)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'app_vehiclecategorytype',
                'ordering': ['ordering', 'category_type'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_vehicleimage',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'app_vehicletype',
            },
        ),
        migrations.AlterModelOptions(
            name='carcategory',
            options={'verbose_name_plural': 'Car Categories (Legacy)'},
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_category', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('melbourne', 'Melbourne'), ('sydney', 'Sydney'), ('brisbane', 'Brisbane'), ('perth', 'Perth'), ('adelaide', 'Adelaide'), ('gold_coast', 'Gold Coast'), ('xi_an', 'Xi An'), ('beijing', 'Beijing'), ('shanghai', 'Shanghai'), ('guangzhou', 'Guangzhou'), ('shenzhen', 'Shenzhen'), ('hangzhou', 'Hangzhou'), ('nanjing', 'Nanjing')], default='melbourne', max_length=50)),
                ('renting_category', models.BooleanField(default=False)),
                ('sipp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('age_youngest_driver', models.IntegerField(default=21)),
                ('num_adults', models.IntegerField(default=0)),
                ('num_children', models.IntegerField(default=0)),
                ('num_large_case', models.IntegerField(default=0)),
                ('num_small_case', models.IntegerField(default=0)),
                ('emission_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_desc_url', models.URLField(blank=True, null=True)),
                ('friendly_description', models.TextField(blank=True, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('comparison_provider1_name', models.CharField(blank=True, max_length=50)),
                ('comparison_provider1_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('comparison_provider2_name', models.CharField(blank=True, max_length=50)),
                ('comparison_provider2_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('locations', models.ManyToManyField(related_name='available_vehicles', to='locations.location')),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cars.vehiclecategorytype')),
                ('image_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='cars.vehicleimage')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cars.vehicletype')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Categories',
                'db_table': 'app_vehiclecategory',
                'ordering': ['category_type__ordering', 'vehicle_category'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_cars', to='cars.vehiclecategory'),
        ),
        migrations.AddField(
            model_name='carcategory',
            name='vehicle_category_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.vehiclecategorytype'),
        ),
        migrations.CreateModel(
            name='VehicleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('icon_class', models.CharField(default='fas fa-check', max_length=50)),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cars.vehiclecategory')),
            ],
        ),
    ]
