# Generated by Django 5.2 on 2025-06-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='app_car',
        ),
    ]
