# Generated by Django 5.2 on 2025-06-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='cars_car',
        ),
        migrations.AlterModelTable(
            name='carcategory',
            table='cars_carcategory',
        ),
        migrations.AlterModelTable(
            name='carfeature',
            table='cars_carfeature',
        ),
        migrations.AlterModelTable(
            name='vehiclecategory',
            table='cars_vehiclecategory',
        ),
        migrations.AlterModelTable(
            name='vehiclecategorytype',
            table='cars_vehiclecategorytype',
        ),
        migrations.AlterModelTable(
            name='vehiclefeature',
            table='cars_vehiclefeature',
        ),
        migrations.AlterModelTable(
            name='vehicleimage',
            table='cars_vehicleimage',
        ),
        migrations.AlterModelTable(
            name='vehicletype',
            table='cars_vehicletype',
        ),
    ]
