# Generated by Django 5.2 on 2025-06-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airport',
            table='app_airport',
        ),
        migrations.AlterModelTable(
            name='city',
            table='app_city',
        ),
        migrations.AlterModelTable(
            name='country',
            table='app_country',
        ),
        migrations.AlterModelTable(
            name='location',
            table='app_location',
        ),
        migrations.AlterModelTable(
            name='masterlocation',
            table='app_masterlocation',
        ),
        migrations.AlterModelTable(
            name='stateprovince',
            table='app_stateprovince',
        ),
    ]
