# Generated by Django 5.2 on 2025-06-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_table_alter_carcategory_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehiclecategorytype',
            table='app_vehiclecategorytype',
        ),
        migrations.AlterModelTable(
            name='vehicleimage',
            table='app_vehicleimage',
        ),
        migrations.AlterModelTable(
            name='vehicletype',
            table='app_vehicletype',
        ),
    ]
