# Generated by Django 5.2 on 2025-04-30 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_vehiclecategorytype_vehicleimage_vehicletype_and_more'),
    ]

    operations = [
        # 修复Car模型中vehicle_category_id字段的问题
        migrations.AlterField(
            model_name='car',
            name='vehicle_category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name='legacy_cars',
                to='cars.vehiclecategory'
            ),
        ),
    ]
