# Generated by Django 5.2 on 2025-04-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20250430_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclecategory',
            name='is_available',
        ),
        migrations.AlterModelTable(
            name='vehiclecategory',
            table='app_vehiclecategory',
        ),
        migrations.AlterModelTable(
            name='vehiclecategorytype',
            table='app_vehiclecategorytype',
        ),
        migrations.AlterModelTable(
            name='vehicleimage',
            table='app_vehicleimage',
        ),
        migrations.AlterModelTable(
            name='vehicletype',
            table='app_vehicletype',
        ),
    ]
