# Generated by Django 5.2 on 2025-06-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_vehiclecategorytype_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_type', models.CharField(max_length=100)),
                ('is_electric', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('fuel_unit', models.CharField(default='Liter', max_length=50)),
                ('fuel_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_default', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('fuel_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_vehiclefuel',
                'ordering': ['fuel_type'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app_vehiclemake',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=100)),
                ('fuel_capacity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'app_vehiclemodel',
                'ordering': ['model_name'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='vehiclecategorytype',
            options={'managed': False, 'ordering': ['ordering', 'category_type']},
        ),
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='vehiclecategory',
            table='app_vehiclecategory',
        ),
    ]
