# Generated by Django 5.2 on 2025-04-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_vehiclecategory_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
