# Generated by Django 5.2 on 2025-06-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='location',
            table='locations_location',
        ),
        migrations.AlterModelTable(
            name='state',
            table='locations_state',
        ),
    ]
