# Generated by Django 5.2 on 2025-06-16 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_alter_airport_table_alter_city_table_and_more'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('flat_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('icon_class', models.CharField(default='fas fa-car', max_length=50)),
                ('is_quantity_option', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Booking Option',
                'verbose_name_plural': 'Booking Options',
                'db_table': 'bookings_bookingoption',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_age', models.PositiveIntegerField()),
                ('damage_waiver', models.BooleanField(default=False)),
                ('extended_area', models.BooleanField(default=False)),
                ('satellite_navigation', models.BooleanField(default=False)),
                ('child_seats', models.PositiveIntegerField(default=0)),
                ('additional_drivers', models.PositiveIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('dropoff_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_bookings', to='locations.location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_bookings', to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings_booking',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('license_number', models.CharField(max_length=50, verbose_name='License Number')),
                ('license_issued_in', models.CharField(max_length=100, verbose_name='Issued In')),
                ('license_expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('license_is_lifetime', models.BooleanField(default=False, verbose_name='Life Time')),
                ('local_address', models.CharField(blank=True, max_length=255, verbose_name='Local Address')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('postcode', models.CharField(max_length=20, verbose_name='Postcode')),
                ('country_of_residence', models.CharField(default='Australia', max_length=100, verbose_name='Country of Residence')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('occupation', models.CharField(blank=True, choices=[('', '-- Please select --'), ('student', 'Student'), ('employed', 'Employed'), ('self_employed', 'Self-employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('other', 'Other')], max_length=50, verbose_name='Occupation')),
                ('mailing_list', models.BooleanField(default=False, verbose_name='Subscribe to Mailing List')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Driver')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'db_table': 'bookings_driver',
            },
        ),
    ]
