# Generated by Django 5.2 on 2025-04-04 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(help_text="Font Awesome icon class (e.g., 'fa-shield-alt')", max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pricing_type', models.CharField(choices=[('per_day', 'Per Day'), ('flat_fee', 'Flat Fee')], default='per_day', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('max_quantity', models.PositiveIntegerField(default=1, help_text='Maximum quantity that can be selected (0 for unlimited)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.addonoption')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
            options={
                'unique_together': {('booking', 'addon')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='addons',
            field=models.ManyToManyField(blank=True, through='bookings.BookingAddon', to='bookings.addonoption'),
        ),
    ]
