# Generated by Django 5.2 on 2025-04-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('flat_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('icon_class', models.CharField(default='fas fa-car', max_length=50)),
                ('is_quantity_option', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_drivers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='child_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='damage_waiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='extended_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='satellite_navigation',
            field=models.BooleanField(default=False),
        ),
    ]
