# Generated by Django 5.2 on 2025-06-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date']},
        ),
        migrations.AlterModelOptions(
            name='bookingoption',
            options={'verbose_name': 'Booking Option', 'verbose_name_plural': 'Booking Options'},
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings_booking',
        ),
        migrations.AlterModelTable(
            name='bookingoption',
            table='bookings_bookingoption',
        ),
        migrations.AlterModelTable(
            name='driver',
            table='bookings_driver',
        ),
    ]
