# Generated by Django 5.2 on 2025-04-08 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingoption_booking_additional_drivers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('license_number', models.CharField(max_length=50, verbose_name='License Number')),
                ('license_issued_in', models.CharField(max_length=100, verbose_name='Issued In')),
                ('license_expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('license_is_lifetime', models.BooleanField(default=False, verbose_name='Life Time')),
                ('local_address', models.CharField(blank=True, max_length=255, verbose_name='Local Address')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('postcode', models.CharField(max_length=20, verbose_name='Postcode')),
                ('country_of_residence', models.CharField(default='Australia', max_length=100, verbose_name='Country of Residence')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('occupation', models.CharField(blank=True, choices=[('', '-- Please select --'), ('student', 'Student'), ('employed', 'Employed'), ('self_employed', 'Self-employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('other', 'Other')], max_length=50, verbose_name='Occupation')),
                ('mailing_list', models.BooleanField(default=False, verbose_name='Subscribe to Mailing List')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Driver')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
    ]
